#!/bin/bash

echo Building Arch Package for SocketProtector...

git_diff_err()
{
  echo "SOURCE TREE IS DIRTY"
  exit 1
}

git diff --quiet || git_diff_err

GITROOT=$(git rev-parse --show-toplevel)
cd $GITROOT

VER=$1
REL=$(git rev-parse --short HEAD)git
TOPDIR=$GITROOT/Build/arch-build
echo "DEST: $TOPDIR Ver: $VER, Release: $REL"

rm -rf $TOPDIR
mkdir -p $TOPDIR

sed -e "s/__VERSION__/$VER/" -e "s/__REL__/$REL/" packaging/PKGBUILD > $TOPDIR/PKGBUILD

cd $TOPDIR
makepkg && echo Done
rm -f SocketProtector-${VER}.pkg.tar.xz
ln -s SocketProtector-${VER}-${REL}-x86_64.pkg.tar.xz SocketProtector-${VER}-x86_64.pkg.tar.xz
