#!/bin/bash

echo Building SocketProtector RPM...

git_diff_err()
{
  echo "SOURCE TREE IS DIRTY"
  exit 1
}

git diff --quiet || git_diff_err

GITROOT=$(git rev-parse --show-toplevel)
cd $GITROOT

VER=$1
DESTDIR=$2
REL=$(git rev-parse --short HEAD)git
RPMTOPDIR=$GITROOT/Build/rpm-build
echo "Ver: $VER, Release: $REL"

# Create tarball
mkdir -p $RPMTOPDIR/{SOURCES,SPECS}
git archive --format=tar --prefix=SocketProtector-${VER}-${REL}/ HEAD | gzip -c > $RPMTOPDIR/SOURCES/SocketProtector-${VER}-${REL}.tar.gz

# Convert git log to RPM's ChangeLog format (shown with rpm -qp --changelog <rpm file>)
sed -e "s/%{ver}/$VER/" -e "s/%{rel}/$REL/" packaging/SocketProtector.spec > $RPMTOPDIR/SPECS/SocketProtector.spec
git log --format="* %cd %aN%n- (%h) %s%d%n" --date=local | sed -r 's/[0-9]+:[0-9]+:[0-9]+ //' >> $RPMTOPDIR/SPECS/SocketProtector.spec

# Build SRC and binary RPMs
rpmbuild    --quiet                       \
            --define "_topdir $RPMTOPDIR" \
            --define "_rpmdir $PWD"       \
            --define "_srcrpmdir $PWD"    \
            --define '_rpmfilename %%{NAME}-%%{VERSION}-%%{RELEASE}.%%{ARCH}.rpm' \
            -ba $RPMTOPDIR/SPECS/SocketProtector.spec &&

rm -rf $RPMTOPDIR &&
echo Done
