#!/bin/bash

echo Building SocketProtector RPM...

GITROOT=$(git rev-parse --show-toplevel)
cd $GITROOT

VER=$1
DESTDIR=$2
REL=$(git rev-parse --short HEAD)git$(git diff --quiet || echo "_dirty")
DIST=""
if [ -e /etc/centos-release ]; then
	DIST=.el$(rpm -q --queryformat='%{VERSION}' centos-release)
elif [ -e /etc/mandrake-release ]; then
	echo "UNTESTED Release on mandrake - check what rpm defines in spec file for dist"
	exit 1
elif [ -e /etc/suse-release ]; then
	echo "UNTESTED Release on SuSE - check what rpm defines in spec file for dist"
	exit 1
elif [ -e /etc/fedora-release ]; then
	echo "UNTESTED Release on fedora core - check what rpm defines in spec file for dist"
	exit 1
else
	DIST=.el$(rpm -q --queryformat='%{VERSION}' redhat-release)
fi
RPMTOPDIR=$GITROOT/Build/rpm-build
echo "Ver: $VER, Release: $REL"

# Create tarball
mkdir -p $RPMTOPDIR/{SOURCES,SPECS}
git archive --format=tar --prefix=SocketProtector-${VER}-${REL}${DIST}/ HEAD | gzip -c > $RPMTOPDIR/SOURCES/SocketProtector-${VER}-${REL}${DIST}.tar.gz

# Convert git log to RPM's ChangeLog format (shown with rpm -qp --changelog <rpm file>)
sed -e "s/%{ver}/$VER/" -e "s/%{rel}/$REL/" packaging/SocketProtector.spec > $RPMTOPDIR/SPECS/SocketProtector.spec
git log --format="* %cd %aN%n- (%h) %s%d%n" --date=local | sed -r 's/[0-9]+:[0-9]+:[0-9]+ //' >> $RPMTOPDIR/SPECS/SocketProtector.spec

# Build SRC and binary RPMs
cd $GITROOT/Build
rpmbuild    -vv --quiet                       \
            --rmsource \
            --define "_topdir $RPMTOPDIR" \
            --define "_prefix $DESTDIR" \
            --define "_rpmdir $PWD"       \
            --define "_srcrpmdir $PWD"    \
            -ba $RPMTOPDIR/SPECS/SocketProtector.spec &&

rm -rf $RPMTOPDIR

